CREATE DATABASE IF NOT EXISTS superlocalizer;
USE superlocalizer;

CREATE TABLE IF NOT EXISTS Company (
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Address VARCHAR(255),
  Email VARCHAR(255),
  Phone VARCHAR(50),
  InsertDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdateDate DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;