CREATE DATABASE IF NOT EXISTS superlocalizer;
USE superlocalizer;

CREATE TABLE IF NOT EXISTS Project (
    Id BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    Name VARCHAR(255) NOT NULL,
    Description TEXT,
    InsertDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateDate DATETIME NULL,
    CompanyId BINARY(16) NOT NULL,
    CONSTRAINT FK_Project_Company FOREIGN KEY (CompanyId) REFERENCES Company(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;