CREATE DATABASE IF NOT EXISTS superlocalizer;
USE superlocalizer;

CREATE TABLE IF NOT EXISTS Property (
    Id BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    `Key` VARCHAR(255) NOT NULL,
    InsertDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateDate DATETIME NULL,
    ProjectId BINARY(16) NOT NULL,
    CONSTRAINT FK_Property_Project FOREIGN KEY (ProjectId) REFERENCES Project(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;