CREATE DATABASE IF NOT EXISTS superlocalizer;
USE superlocalizer;

CREATE TABLE IF NOT EXISTS Property (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Key` VARCHAR(255) NOT NULL,
    InsertDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateDate DATETIME NULL,
    ProjectId INT NOT NULL,
    CONSTRAINT FK_Property_Project FOREIGN KEY (ProjectId) REFERENCES Project(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;