CREATE DATABASE IF NOT EXISTS superlocalizer;
USE superlocalizer;

CREATE TABLE IF NOT EXISTS Value (
    Id BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    PropertyKey VARCHAR(255) NOT NULL,
    Language VARCHAR(50) NOT NULL,
    Text TEXT,
    IsVerified TINYINT(1) NOT NULL DEFAULT 0,
    IsReviewed TINYINT(1) NOT NULL DEFAULT 0,
    InsertDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateDate DATETIME NULL,
    PropertyId BINARY(16) NOT NULL,
    CONSTRAINT FK_Value_Property FOREIGN KEY (PropertyId) REFERENCES Property(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;