CREATE DATABASE IF NOT EXISTS superlocalizer;
USE superlocalizer;

CREATE TABLE IF NOT EXISTS Comment (
    Id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    ValueKey VARCHAR(255) NOT NULL,
    Author VARCHAR(255) NOT NULL,
    Text TEXT,
    InsertDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateDate DATETIME NULL,
    ValueId INT NOT NULL,
    CONSTRAINT FK_Comment_Value FOREIGN KEY (ValueId) REFERENCES `Value`(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;