CREATE DATABASE IF NOT EXISTS superlocalizer;
USE superlocalizer;

CREATE TABLE IF NOT EXISTS Comment (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ValueKey NVARCHAR(255) NOT NULL,
    Author NVARCHAR(255) NOT NULL,
    Text NVARCHAR(MAX),
    InsertDate DATETIME NOT NULL DEFAULT(GETDATE()),
    UpdateDate DATETIME NULL,
    ValueId INT NOT NULL,
    CONSTRAINT FK_Comment_Value FOREIGN KEY (ValueId) REFERENCES [Value](Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;