CREATE DATABASE IF NOT EXISTS superlocalizer;
USE superlocalizer;

CREATE TABLE IF NOT EXISTS ProjectSnapshot (
    Id BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    ProjectId BINARY(16) NOT NULL,
    SnapshotData LONGTEXT,
    InsertDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateDate DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;