CREATE DATABASE IF NOT EXISTS superlocalizer;
USE superlocalizer;

CREATE TABLE IF NOT EXISTS ProjectSnapshot (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ProjectId INT NOT NULL,
    SnapshotData LONGTEXT,
    InsertDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateDate DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;