###
# @name login
POST http://localhost:5000/auth/signin
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
###
POST http://localhost:5000/property/search
accept: text/plain
Content-Type: application/json

{
  "page": 1,
  "size": 10
}
###
PATCH http://localhost:5000/property/connectivityAlerts.offline/it
accept: */*
Content-Type: application/json

{
  "text": "PIPPOOOOO",
  "isVerified": true,
  "isReviewed": true
}
###
GET http://localhost:5000/project/1/property/all-languages
Authorization: Bearer {{login.response.body.token}}
accept: application/json
###