### Registration Flow
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "email": "admin"
}
###
# @name login
POST http://localhost:5000/auth/signin
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
### Create a new company
POST http://localhost:5000/company
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "name": "Supertext",
  "address": "address",
  "email": "email@email.com",
  "phone": "1234567890"
}
### Get the company by ID
GET http://localhost:5000/company/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}
### Create a new project for the company
POST http://localhost:5000/company/1/project
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "name": "Mt.Ui interface",
  "description": "This is a test project"
}
### Get the project by ID
GET http://localhost:5000/company/1/project/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}
### Setup main project for the user
PUT http://localhost:5000/company/1/project/1/user
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "username": "admin",
  "projectId": 1
}
### Get the user info
GET http://localhost:5000/auth/user
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}
###