### Import files
POST http://localhost:5000/api/sync/import
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="mainLanguage"

de-CH
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="localization_de-CH.json"
Content-Type: application/json

< ../SupertextLocalisation/de-CH/localization_de-CH.json
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="localization_de-DE.json"
Content-Type: application/json

< ../SupertextLocalisation/de-DE/localization_de-DE.json
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="localization_fr.json"
Content-Type: application/json

< ../SupertextLocalisation/fr/localization_fr.json
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="localization_en.json"
Content-Type: application/json

< ../SupertextLocalisation/en/localization_en.json
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="localization_it.json"
Content-Type: application/json

< ../SupertextLocalisation/it/localization_it.json
------WebKitFormBoundary7MA4YWxkTrZu0gW--
### Export files
POST http://localhost:5000/api/sync/export
Content-Type: application/json